apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: quarkus-play-serverless
  namespace: quarkus-ns
spec:
  template:
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/quarkus-ns/quarkus-app:1.0